# Generated by Django 4.0.4 on 2022-04-17 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viva_app1', '0002_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='feedback',
        ),
    ]
