# Generated by Django 4.0.4 on 2022-05-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viva_app1', '0005_flames_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='gender',
        ),
        migrations.AddField(
            model_name='contact',
            name='rating',
            field=models.CharField(default=None, max_length=1),
            preserve_default=False,
        ),
    ]
